---

language: bash

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - env:
        - PACKER_VERSION='1.2.1'
        - PACKER_VERSION=''

sudo: enabled

branches:
  only:
    - master

script:
    - sudo bash install-packer.sh $PACKER_VERSION
