---

env:
  - PACKER_VERSION='1.2.1'
  - PACKER_VERSION=''

language: bash

matrix:
  include:
    - dist: xenial
    - dist: bionic

sudo: enabled

branches:
  only:
    - master

script:
    - sudo bash install-packer.sh $PACKER_VERSION
