---

matrix:
  include:
    - dist: trusty
    - dist: xenial

branches:
  only:
    - master

language: bash
sudo: enabled

script:
    - sudo bash install-packer.sh 1.2.0
    - sudo bash install-packer.sh
