---

#language: bash

matrix:
  include:
    - dist: trusty
      language: bash
    - dist: xenial
      language: bash

sudo: enabled

branches:
  only:
    - master

script:
    - sudo bash install-packer.sh 1.2.0
    - sudo bash install-packer.sh
