---

#services:
#  - docker

matrix:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal

branches:
  only:
    - master

language: bash
sudo: enabled

script:
  - sudo bash ./tests/test.sh
